"""
Temperature response functions for AIA channels.

This module provides functions to obtain temperature response functions
for SDO/AIA EUV channels, either via aiapy (if available) or using
pre-computed fallback tables.

References:
    - Boerner et al. (2012), Solar Physics 275, 41-66
    - Boerner et al. (2014), Solar Physics 289, 2377-2397
"""

import os
from datetime import datetime
from typing import List, Optional, Union

import numpy as np

# Check for aiapy availability
try:
    import aiapy.response
    from aiapy.calibrate import degradation
    HAS_AIAPY = True
except ImportError:
    HAS_AIAPY = False

# Check for fiasco (CHIANTI) availability — provides the contribution
# function G(lambda, T) needed to recompute K(T) after aiapy 0.12 dropped
# Channel.temperature_response.
try:
    import fiasco  # noqa: F401
    HAS_FIASCO = True
except ImportError:
    HAS_FIASCO = False

# Default electron density and abundance set for the CHIANTI synthesis.
# Coronal (Feldman) abundances match the SSW aia_get_response convention.
DEFAULT_DEM_DENSITY_CM3 = 1e9
DEFAULT_DEM_ABUNDANCE = "sun_coronal_1992_feldman_ext"
# Wavelength band (Angstrom) over which AIA EUV channels have response;
# transitions outside are skipped (and ions with none are not solved).
AIA_RESPONSE_BAND = (80.0, 360.0)

# Standard AIA EUV wavelengths for DEM analysis
AIA_DEM_WAVELENGTHS = [94, 131, 171, 193, 211, 335]

# Default temperature grid (log10 K)
DEFAULT_LOGT_MIN = 5.5
DEFAULT_LOGT_MAX = 7.5
DEFAULT_LOGT_BINS = 100


def get_default_temperatures(
    logt_min: float = DEFAULT_LOGT_MIN,
    logt_max: float = DEFAULT_LOGT_MAX,
    n_bins: int = DEFAULT_LOGT_BINS,
) -> np.ndarray:
    """
    Get default temperature array for DEM analysis.

    Parameters
    ----------
    logt_min : float, optional
        Minimum log10(T/K), default 5.5.
    logt_max : float, optional
        Maximum log10(T/K), default 7.5.
    n_bins : int, optional
        Number of temperature bins, default 100.

    Returns
    -------
    np.ndarray
        Temperature array in Kelvin.

    Examples
    --------
    >>> temps = get_default_temperatures()
    >>> temps.shape
    (100,)
    >>> np.log10(temps[0])  # doctest: +ELLIPSIS
    5.5...
    """
    logt = np.linspace(logt_min, logt_max, n_bins)
    return 10.0 ** logt


def get_temperature_response(
    wavelengths: Optional[List[int]] = None,
    temperatures: Optional[np.ndarray] = None,
    time: Optional[datetime] = None,
    include_degradation: bool = True,
    ssw_table_path: Optional[Union[str, os.PathLike]] = None,
    ssw_response_key: str = "response_v10_en",
) -> np.ndarray:
    """
    Get AIA temperature response functions.

    Computes the temperature response K(T) for each AIA channel,
    which relates the observed intensity to the DEM:
        I = integral(K(T) * DEM(T) * dT)

    Sources are tried in this priority order:

    1. ``ssw_table_path`` — an SSW-derived ``.npz`` table generated by
       ``aia_get_response.pro`` (canonical IDL reference; CHIANTI-based).
       Preferred when available; reuses the calibration used by demregpy
       and the official AIA pipeline.
    2. ``fiasco`` + ``aiapy`` (when both installed) — recompute K(T) from
       CHIANTI contribution functions folded with the aiapy wavelength
       response (``_get_fiasco_response``). This is the live replacement
       for aiapy's removed ``Channel.temperature_response`` and is
       research-grade, but **slow** (one-time; persist the result).
    3. ``aiapy`` alone — disabled (aiapy 0.12 removed
       ``Channel.temperature_response``); raises with a pointer.
    4. The built-in Gaussian fallback (``_get_fallback_response``), used
       only when aiapy is unavailable and no SSW table is given. This emits
       a `UserWarning` and is **not** suitable for research-quality DEM
       inversion.

    Parameters
    ----------
    wavelengths : list of int, optional
        AIA wavelengths in Angstroms. Default: [94, 131, 171, 193, 211, 335].
    temperatures : np.ndarray, optional
        Temperature array in Kelvin. Default: logarithmic grid from 10^5.5 to 10^7.5 K.
    time : datetime, optional
        Observation time for degradation correction. Default: None (no degradation).
    include_degradation : bool, optional
        Whether to include time-dependent degradation. Default: True.
        Ignored when ``ssw_table_path`` is supplied — the SSW file
        already encodes its calibration.
    ssw_table_path : path-like, optional
        Path to an SSW-derived response ``.npz`` (see
        :func:`load_ssw_temperature_response`). When given, this source
        is used and the aiapy / fallback paths are bypassed.
    ssw_response_key : str, optional
        Key in the SSW ``.npz`` selecting which calibration variant to
        load. Default ``"response_v10_en"`` (V10 effective area with EVE
        normalization, no time-dependent degradation correction).

    Returns
    -------
    np.ndarray
        Temperature response matrix, shape (n_temperatures, n_wavelengths).
        Units: DN cm^5 s^-1 pixel^-1.

    References
    ----------
    - Boerner et al. (2012), Solar Physics 275, 41-66
    - Boerner et al. (2014), Solar Physics 289, 2377-2397
    """
    if wavelengths is None:
        wavelengths = AIA_DEM_WAVELENGTHS

    if temperatures is None:
        temperatures = get_default_temperatures()

    if ssw_table_path is not None:
        log_temperatures = np.log10(np.asarray(temperatures, dtype=np.float64))
        return load_ssw_temperature_response(
            ssw_table_path,
            log_temperatures=log_temperatures,
            wavelengths=wavelengths,
            response_key=ssw_response_key,
        )

    # Preferred live source: CHIANTI (fiasco) contribution function folded
    # with the aiapy wavelength response. Requires both.
    if HAS_FIASCO and HAS_AIAPY:
        return _get_fiasco_response(wavelengths, temperatures)

    if not HAS_AIAPY:
        return _get_fallback_response(wavelengths, temperatures)

    return _get_aiapy_response(
        wavelengths, temperatures, time, include_degradation
    )


def load_ssw_temperature_response(
    path: Union[str, os.PathLike],
    *,
    log_temperatures: Optional[np.ndarray] = None,
    wavelengths: Optional[List[int]] = None,
    response_key: str = "response_v10_en",
) -> np.ndarray:
    """
    Load an SSW-derived AIA temperature response from a ``.npz`` archive.

    The archive is expected to follow the convention established by
    ``aia_get_response.pro`` (IDL SolarSoftWare) as exposed by demregpy:

    - ``log_temperature``: 1D array of ``log10(T/K)`` values, length ``n_T``.
    - ``channels``: 1D integer array of channel wavelengths in Angstroms,
      length ``n_lambda``.
    - One or more response arrays of shape ``(n_lambda, n_T)``, with
      common keys ``response_v9_en``, ``response_v10_en``,
      ``response_v10_en_nb``. The key is selected by ``response_key``.

    Parameters
    ----------
    path : path-like
        Path to the ``.npz`` archive.
    log_temperatures : np.ndarray, optional
        Target ``log10(T/K)`` grid for linear interpolation along the
        temperature axis. If None, the response is returned on the source
        grid stored in the file.
    wavelengths : list of int, optional
        Wavelengths to extract, in the desired output order. If None,
        :data:`AIA_DEM_WAVELENGTHS` is used.
    response_key : str
        Which response variant to read from the archive.

    Returns
    -------
    np.ndarray
        Response matrix of shape ``(n_temperatures, n_wavelengths)``,
        consistent with :func:`get_temperature_response`. Units inherit
        from the source file (typically DN cm^5 s^-1 pixel^-1).

    Raises
    ------
    KeyError
        If ``response_key`` is not present in the archive, or if any of
        ``wavelengths`` is missing from ``channels``.
    ValueError
        If the response array shape disagrees with the channel / log-T
        sizes, or if the requested ``log_temperatures`` fall outside the
        source grid (no extrapolation).
    """
    target_waves = list(wavelengths) if wavelengths is not None else list(AIA_DEM_WAVELENGTHS)

    with np.load(path, allow_pickle=False) as data:
        if response_key not in data.files:
            available = sorted(k for k in data.files if k.startswith("response"))
            raise KeyError(
                f"response_key {response_key!r} not in {os.fspath(path)!r}; "
                f"available response keys: {available}"
            )
        raw = np.asarray(data[response_key], dtype=np.float64)
        src_channels = np.asarray(data["channels"]).astype(int).tolist()
        src_log_t = np.asarray(data["log_temperature"], dtype=np.float64)

    if raw.shape != (len(src_channels), src_log_t.size):
        raise ValueError(
            f"response array shape {raw.shape} does not match "
            f"(n_channels={len(src_channels)}, n_log_t={src_log_t.size})"
        )

    missing = [w for w in target_waves if w not in src_channels]
    if missing:
        raise KeyError(
            f"wavelengths {missing} not found in SSW table; "
            f"available: {src_channels}"
        )

    channel_indices = [src_channels.index(w) for w in target_waves]
    raw_selected = raw[channel_indices]  # shape (n_waves, n_T_src)

    if log_temperatures is None:
        return raw_selected.T  # (n_T_src, n_waves)

    target_log_t = np.asarray(log_temperatures, dtype=np.float64)
    src_min, src_max = float(src_log_t.min()), float(src_log_t.max())
    tol = 1e-9
    if target_log_t.min() < src_min - tol or target_log_t.max() > src_max + tol:
        raise ValueError(
            f"target log T range [{target_log_t.min()}, {target_log_t.max()}] "
            f"falls outside the source grid [{src_min}, {src_max}]; "
            "extrapolation is not allowed"
        )

    interpolated = np.empty((len(target_waves), target_log_t.size), dtype=np.float64)
    # `np.interp` requires monotonically increasing xp; sort if needed.
    if not np.all(np.diff(src_log_t) > 0):
        order = np.argsort(src_log_t)
        src_log_t = src_log_t[order]
        raw_selected = raw_selected[:, order]
    for i in range(len(target_waves)):
        interpolated[i] = np.interp(target_log_t, src_log_t, raw_selected[i])
    return interpolated.T  # (n_T_target, n_waves)


def _fold_lines_into_channel(
    g_photon: np.ndarray,
    line_wavelength: np.ndarray,
    channel_wavelength: np.ndarray,
    channel_response: np.ndarray,
    plate_scale_sr: float,
) -> np.ndarray:
    """Fold per-line contribution functions into one channel's K(T).

    K(T) = (Omega_pix / 4pi) * sum_lines g_photon(T, line) * R(lambda_line)

    Parameters
    ----------
    g_photon : np.ndarray
        Per-line contribution function already converted to photon units,
        shape ``(n_T, n_lines)`` in ``cm^3 photon / s``.
    line_wavelength : np.ndarray
        Wavelength of each line, shape ``(n_lines,)``, Angstrom.
    channel_wavelength, channel_response : np.ndarray
        The channel's wavelength grid (Angstrom) and wavelength response
        (``cm^2 DN / photon``); response is interpolated onto the lines
        (0 outside the grid).
    plate_scale_sr : float
        Pixel solid angle in steradian.

    Returns
    -------
    np.ndarray
        ``(n_T,)`` response in ``DN cm^5 s^-1 pixel^-1``.
    """
    r_at_line = np.interp(
        line_wavelength, channel_wavelength, channel_response, left=0.0, right=0.0
    )
    return (plate_scale_sr / (4.0 * np.pi)) * (g_photon * r_at_line).sum(axis=1)


def _get_fiasco_response(
    wavelengths: List[int],
    temperatures: np.ndarray,
    *,
    density_cm3: float = DEFAULT_DEM_DENSITY_CM3,
    abundance: str = DEFAULT_DEM_ABUNDANCE,
    band: tuple = AIA_RESPONSE_BAND,
) -> np.ndarray:
    """Compute AIA temperature response via CHIANTI (fiasco) + aiapy.

    Replaces the aiapy ``Channel.temperature_response`` removed in aiapy
    0.12. For each AIA channel,

        K_i(T) = (Omega_pix / 4pi)
                 * sum_transitions G_ij(T) / (hc/lambda_ij) * R_i(lambda_ij)

    where ``G_ij`` is the CHIANTI contribution function (``cm^3 erg/s``,
    from `fiasco.Ion.contribution_function`), ``hc/lambda`` converts energy
    to photons, ``R_i`` is the aiapy wavelength response
    (``cm^2 DN/photon``), and ``Omega_pix`` is the pixel solid angle. The
    result is in ``DN cm^5 s^-1 pixel^-1``.

    Only ions with bound-bound transitions inside ``band`` are solved (the
    level-population solve is skipped for ions with no AIA-band lines).
    Ions whose CHIANTI data is incomplete are skipped.

    .. note::
        This is a **one-time, slow** computation (order tens of minutes —
        it solves level populations for every contributing CHIANTI ion).
        Persist the result (e.g. via ``egghouse.database`` or a saved
        ``.npz``) rather than recomputing per run. Requires the CHIANTI
        database (``fiasco`` downloads it on first use).

        Time-dependent degradation is **not** folded in here (the base
        instrument response is returned); apply it at the image level via
        ``aiapy.calibrate.correct_degradation``.

    Returns
    -------
    np.ndarray
        Response matrix, shape ``(n_temperatures, n_wavelengths)``.
    """
    import astropy.constants as const
    import astropy.units as u
    from aiapy.response import Channel

    temperatures = np.asarray(temperatures, dtype=np.float64)
    T = temperatures * u.K
    n_e = density_cm3 * u.cm**-3

    # Per-channel wavelength response and pixel solid angle (aiapy).
    channel_data = []
    for w in wavelengths:
        ch = Channel(int(w) * u.angstrom)
        channel_data.append((
            ch.wavelength.to_value("angstrom"),
            ch.wavelength_response().to_value("cm2 DN / ph"),
            ch.plate_scale.to_value("sr / pix"),
        ))

    K = np.zeros((len(wavelengths), temperatures.size), dtype=np.float64)
    hc = (const.h * const.c).to_value("erg angstrom")  # erg * Angstrom

    for ion_name in fiasco.list_ions():
        try:
            ion = fiasco.Ion(ion_name, T, abundance=abundance)
            line_wl = ion.transitions.wavelength.to_value("angstrom")
            in_band = (line_wl >= band[0]) & (line_wl <= band[1])
            if not in_band.any():
                continue
            g = ion.contribution_function(n_e).to_value("cm3 erg / s")[:, 0, :]
            line_wl = line_wl[in_band]
            g_photon = g[:, in_band] / (hc / line_wl)  # cm^3 photon / s
            for i, (ch_wl, ch_r, omega) in enumerate(channel_data):
                K[i] += _fold_lines_into_channel(g_photon, line_wl, ch_wl, ch_r, omega)
        except Exception:
            # Ions with incomplete CHIANTI data are skipped.
            continue

    return K.T  # (n_temperatures, n_wavelengths)


def _get_aiapy_response(
    wavelengths: List[int],
    temperatures: np.ndarray,
    time: Optional[datetime],
    include_degradation: bool,
) -> np.ndarray:
    """
    Compute temperature response via aiapy.

    Currently disabled: aiapy 0.12 removed ``Channel.temperature_response``
    because computing K(T) correctly requires CHIANTI atomic data that
    aiapy does not ship. A correct re-implementation would multiply
    ``Channel.wavelength_response`` by a CHIANTI-derived contribution
    function (e.g. via ``fiasco``) and integrate over wavelength.

    Until that path is wired up, this function raises ``NotImplementedError``
    with a clear pointer to :func:`load_ssw_temperature_response`, which
    consumes the canonical SSW ``aia_get_response`` output instead.
    """
    raise NotImplementedError(
        "egghouse.sdo.dem._get_aiapy_response is disabled for aiapy >= 0.12 "
        "(Channel.temperature_response was removed upstream). "
        "Supply `ssw_table_path` to get_temperature_response(), or call "
        "load_ssw_temperature_response() directly."
    )


def _get_fallback_response(
    wavelengths: List[int],
    temperatures: np.ndarray,
) -> np.ndarray:
    """
    Get approximate temperature response without aiapy.

    This provides rough estimates based on characteristic temperatures
    of each AIA channel. For accurate DEM analysis, install aiapy.

    Parameters
    ----------
    wavelengths : list of int
        AIA wavelengths.
    temperatures : np.ndarray
        Temperature array in Kelvin.

    Returns
    -------
    np.ndarray
        Approximate response matrix (n_temps, n_wavelengths).

    Warnings
    --------
    This is a simplified approximation. For research-quality DEM analysis,
    please install aiapy for accurate temperature response functions.
    """
    import warnings

    warnings.warn(
        "Using approximate temperature response. "
        "Install aiapy for accurate DEM analysis: pip install aiapy",
        UserWarning,
    )

    # Characteristic peak temperatures (log10 K) and widths for each channel
    # Based on Lemen et al. (2012)
    channel_params = {
        94: {"logt_peak": 6.8, "width": 0.3, "amplitude": 1e-26},  # Fe XVIII
        131: {"logt_peak": 5.6, "width": 0.4, "amplitude": 5e-27},  # Fe VIII, XXI
        171: {"logt_peak": 5.9, "width": 0.3, "amplitude": 1e-25},  # Fe IX
        193: {"logt_peak": 6.2, "width": 0.4, "amplitude": 5e-26},  # Fe XII, XXIV
        211: {"logt_peak": 6.3, "width": 0.3, "amplitude": 3e-26},  # Fe XIV
        335: {"logt_peak": 6.4, "width": 0.4, "amplitude": 5e-27},  # Fe XVI
    }

    n_temps = len(temperatures)
    n_waves = len(wavelengths)
    response = np.zeros((n_temps, n_waves), dtype=np.float64)

    logt = np.log10(temperatures)

    for i, wave in enumerate(wavelengths):
        if wave in channel_params:
            params = channel_params[wave]
            # Simple Gaussian approximation
            response[:, i] = params["amplitude"] * np.exp(
                -0.5 * ((logt - params["logt_peak"]) / params["width"]) ** 2
            )
        else:
            raise ValueError(f"Unknown wavelength: {wave} Angstrom")

    return response


def compute_response_derivative(
    response: np.ndarray,
    temperatures: np.ndarray,
) -> np.ndarray:
    """
    Compute temperature derivative of response functions.

    Used in SITES algorithm for DEM inversion.

    Parameters
    ----------
    response : np.ndarray
        Temperature response matrix (n_temps, n_wavelengths).
    temperatures : np.ndarray
        Temperature array in Kelvin.

    Returns
    -------
    np.ndarray
        Response derivative dK/dT, same shape as response.
    """
    # Use log temperature for numerical stability
    logt = np.log10(temperatures)
    dlogt = np.gradient(logt)

    # Compute gradient along temperature axis
    dresponse = np.gradient(response, axis=0) / dlogt[:, np.newaxis]

    return dresponse


def get_response_weights(
    response: np.ndarray,
    method: str = "sum",
) -> np.ndarray:
    """
    Compute weights from temperature response for DEM initialization.

    Parameters
    ----------
    response : np.ndarray
        Temperature response matrix (n_temps, n_wavelengths).
    method : str, optional
        Weighting method: "sum", "max", or "mean". Default: "sum".

    Returns
    -------
    np.ndarray
        Weight array of shape (n_temps,).
    """
    if method == "sum":
        return np.sum(response, axis=1)
    elif method == "max":
        return np.max(response, axis=1)
    elif method == "mean":
        return np.mean(response, axis=1)
    else:
        raise ValueError(f"Unknown method: {method}")
